export const STATIC_CHANGE_ISMENU='STATIC_CHANGE_ISMENU'
export const STATIC_CHANGE_POPUP='STATIC_CHANGE_POPUP'
export const STATIC_CHANGE_TITLE='STATIC_CHANGE_TITLE' //修改标题
export const STATIC_CHANGE_ADDR="STATIC_CHANGE_ADDR" //更新头部地址